// SPDX-License-Identifier: MIT
/**
 * Idempotent Stripe products + prices sync.
 *
 * Reads pricing/tiers.config.ts and ensures each `stripeBuyable: true` tier
 * has a Stripe product (matched by metadata.tplane_tier_slug) and two active
 * recurring prices: one monthly and one annual. Writes the resulting price
 * IDs to pricing/tiers.generated.ts.
 *
 * Usage:
 *   STRIPE_SECRET_KEY=sk_test_... pnpm tsx scripts/stripe/sync-products.ts
 *
 * Re-running is safe: products are matched by metadata, prices are reused if
 * the unit_amount and interval match, otherwise stale prices are archived
 * and new ones created.
 */
import Stripe from 'stripe';
import fs from 'node:fs';
import path from 'node:path';
import {
  BUYABLE_TIERS,
  type TierConfig,
  type BillingCycle,
} from '../../pricing/tiers.config';

const METADATA_KEY = 'tplane_tier_slug';
const CYCLE_KEY = 'tplane_billing_cycle';

interface SyncedPriceIds {
  monthly: string;
  annual: string;
}

async function findOrCreateProduct(stripe: Stripe, tier: TierConfig): Promise<Stripe.Product> {
  const search = await stripe.products.search({
    query: `metadata['${METADATA_KEY}']:'${tier.slug}'`,
    limit: 1,
  });
  const existing = search.data[0];
  if (existing) {
    if (existing.name !== tier.name || existing.active === false) {
      return stripe.products.update(existing.id, { name: tier.name, active: true });
    }
    return existing;
  }
  return stripe.products.create({
    name: tier.name,
    metadata: { [METADATA_KEY]: tier.slug },
  });
}

async function findOrCreatePrice(
  stripe: Stripe,
  product: Stripe.Product,
  tier: TierConfig,
  cycle: BillingCycle,
): Promise<Stripe.Price> {
  const cents = tier.prices[cycle].cents;
  if (cents === null) {
    throw new Error(`Tier ${tier.slug} cycle ${cycle} has null cents but is marked stripeBuyable`);
  }
  const interval: Stripe.PriceCreateParams.Recurring.Interval = cycle === 'monthly' ? 'month' : 'year';

  const prices = await stripe.prices.list({ product: product.id, active: true, limit: 20 });
  const match = prices.data.find(
    (p) =>
      p.unit_amount === cents &&
      p.currency === 'usd' &&
      p.type === 'recurring' &&
      p.recurring?.interval === interval,
  );
  if (match) return match;

  // Archive any active recurring prices for this cycle that don't match
  // (one active price per (tier, cycle)).
  for (const stale of prices.data) {
    if (stale.type === 'recurring' && stale.recurring?.interval === interval) {
      await stripe.prices.update(stale.id, { active: false });
    }
  }

  return stripe.prices.create({
    product: product.id,
    currency: 'usd',
    unit_amount: cents,
    recurring: { interval },
    metadata: { [METADATA_KEY]: tier.slug, [CYCLE_KEY]: cycle },
  });
}

function renderGeneratedFile(idsBySlug: Record<string, SyncedPriceIds>): string {
  const entries = Object.entries(idsBySlug)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(
      ([slug, ids]) =>
        `  ${slug}: { monthly: ${JSON.stringify(ids.monthly)}, annual: ${JSON.stringify(ids.annual)} },`,
    )
    .join('\n');
  return `// SPDX-License-Identifier: MIT
// Generated by scripts/stripe/sync-products.ts. Do not edit by hand.
import type { TierSlug, BillingCycle } from './tiers.config';

type BuyableSlug = Exclude<TierSlug, 'community' | 'enterprise'>;

export const STRIPE_PRICE_IDS: Partial<Record<BuyableSlug, Record<BillingCycle, string>>> = {
${entries}
};
`;
}

export async function syncProducts(stripe: Stripe): Promise<Record<string, SyncedPriceIds>> {
  const idsBySlug: Record<string, SyncedPriceIds> = {};
  for (const tier of BUYABLE_TIERS) {
    const product = await findOrCreateProduct(stripe, tier);
    const monthly = await findOrCreatePrice(stripe, product, tier, 'monthly');
    const annual = await findOrCreatePrice(stripe, product, tier, 'annual');
    idsBySlug[tier.slug] = { monthly: monthly.id, annual: annual.id };
    console.log(
      `✓ ${tier.slug}: product=${product.id} monthly=${monthly.id} (${tier.prices.monthly.cents}¢) annual=${annual.id} (${tier.prices.annual.cents}¢)`,
    );
  }
  return idsBySlug;
}

async function main(): Promise<void> {
  const key = process.env['STRIPE_SECRET_KEY'];
  if (!key || !key.startsWith('sk_')) {
    throw new Error('STRIPE_SECRET_KEY must be set and begin with sk_');
  }
  const stripe = new Stripe(key);
  const ids = await syncProducts(stripe);
  const outPath = path.join(process.cwd(), 'pricing', 'tiers.generated.ts');
  fs.writeFileSync(outPath, renderGeneratedFile(ids));
  console.log(`\nWrote ${outPath}`);
}

// Only run when executed directly (not when imported by tests).
// tsx compiles to CJS so `require.main === module` is reliable here.
if (require.main === module) {
  main().catch((err: unknown) => {
    console.error(err);
    process.exit(1);
  });
}
