// SPDX-License-Identifier: MIT
/**
 * Idempotent Stripe products + prices sync.
 *
 * Reads pricing/tiers.config.ts and ensures each `stripeBuyable: true` tier
 * has a Stripe product (matched by metadata.ngaf_tier_slug) and exactly one
 * active one-time price. Writes the resulting price IDs to
 * pricing/tiers.generated.ts.
 *
 * Usage:
 *   STRIPE_SECRET_KEY=sk_test_... pnpm tsx scripts/stripe/sync-products.ts
 *
 * Re-running is safe: products are matched by metadata, prices are reused if
 * the unit_amount matches, otherwise the old price is archived and a new one
 * created.
 */
import Stripe from 'stripe';
import fs from 'node:fs';
import path from 'node:path';
import { BUYABLE_TIERS, type TierConfig } from '../../pricing/tiers.config';

const METADATA_KEY = 'ngaf_tier_slug';

async function findOrCreateProduct(stripe: Stripe, tier: TierConfig): Promise<Stripe.Product> {
  const search = await stripe.products.search({
    query: `metadata['${METADATA_KEY}']:'${tier.slug}'`,
    limit: 1,
  });
  const existing = search.data[0];
  if (existing) {
    if (existing.name !== tier.name || existing.active === false) {
      return stripe.products.update(existing.id, { name: tier.name, active: true });
    }
    return existing;
  }
  return stripe.products.create({
    name: tier.name,
    metadata: { [METADATA_KEY]: tier.slug },
  });
}

async function findOrCreatePrice(
  stripe: Stripe,
  product: Stripe.Product,
  tier: TierConfig,
): Promise<Stripe.Price> {
  if (tier.priceCents === null) {
    throw new Error(`Tier ${tier.slug} has null priceCents but is marked stripeBuyable`);
  }
  const prices = await stripe.prices.list({ product: product.id, active: true, limit: 10 });
  const match = prices.data.find(
    (p) => p.unit_amount === tier.priceCents && p.currency === 'usd' && p.type === 'one_time',
  );
  if (match) return match;

  // Archive any active prices that don't match (one active price per tier).
  for (const stale of prices.data) {
    await stripe.prices.update(stale.id, { active: false });
  }

  return stripe.prices.create({
    product: product.id,
    currency: 'usd',
    unit_amount: tier.priceCents,
    metadata: { [METADATA_KEY]: tier.slug },
  });
}

function renderGeneratedFile(idsBySlug: Record<string, string>): string {
  const entries = Object.entries(idsBySlug)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([k, v]) => `  ${k}: ${JSON.stringify(v)},`)
    .join('\n');
  return `// SPDX-License-Identifier: MIT
// Generated by scripts/stripe/sync-products.ts. Do not edit by hand.
import type { TierSlug } from './tiers.config';

export const STRIPE_PRICE_IDS: Partial<Record<Exclude<TierSlug, 'community' | 'enterprise'>, string>> = {
${entries}
};
`;
}

export async function syncProducts(stripe: Stripe): Promise<Record<string, string>> {
  const idsBySlug: Record<string, string> = {};
  for (const tier of BUYABLE_TIERS) {
    const product = await findOrCreateProduct(stripe, tier);
    const price = await findOrCreatePrice(stripe, product, tier);
    idsBySlug[tier.slug] = price.id;
    console.log(`✓ ${tier.slug}: product=${product.id} price=${price.id} (${tier.priceCents}¢)`);
  }
  return idsBySlug;
}

async function main(): Promise<void> {
  const key = process.env['STRIPE_SECRET_KEY'];
  if (!key || !key.startsWith('sk_')) {
    throw new Error('STRIPE_SECRET_KEY must be set and begin with sk_');
  }
  const stripe = new Stripe(key);
  const ids = await syncProducts(stripe);
  const outPath = path.join(process.cwd(), 'pricing', 'tiers.generated.ts');
  fs.writeFileSync(outPath, renderGeneratedFile(ids));
  console.log(`\nWrote ${outPath}`);
}

// Only run when executed directly (not when imported by tests).
// tsx compiles to CJS so `require.main === module` is reliable here.
if (require.main === module) {
  main().catch((err: unknown) => {
    console.error(err);
    process.exit(1);
  });
}
