import { mkdir, copyFile, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import bridge from './bridge.cjs';
const name = process.argv[2];
if (!['chat', 'langgraph', 'ag-ui', 'render'].includes(name))
  throw new Error('Unknown install collector package');
const source = dirname(fileURLToPath(import.meta.url));
const target = resolve(source, '../..', name);
const pkg = JSON.parse(await readFile(join(target, 'package.json'), 'utf8'));
if (
  pkg.name !== `@threadplane/${name}` ||
  pkg.scripts?.postinstall !== 'node install/postinstall.cjs'
)
  throw new Error('Build must preserve the explicit install lifecycle');
await mkdir(join(target, '.install-collector'), { recursive: true });
// Always publish an inert export, regardless of prior local lifecycle runs.
await writeFile(
  join(target, '.install-collector/development-install.mjs'),
  bridge.moduleSource(null)
);
await writeFile(
  join(target, '.install-collector/development-install.d.ts'),
  'export declare const installationToken: string | null;\n'
);
// ng-packagr cannot resolve a source package.json import from its temporary ESM tree.
// Embed only the publisher's release version before compiling; manifest changes invalidate this target.
const versionPath = join(target, 'src/lib/package-version.ts');
const versionSource = `// Generated by the package preparation target from package.json.\n// prettier-ignore\nexport const THREADPLANE_PACKAGE_VERSION = ${JSON.stringify(
  pkg.version
)};\n`;
if ((await readFile(versionPath, 'utf8').catch(() => '')) !== versionSource)
  await writeFile(versionPath, versionSource);
for (const file of [
  'collector',
  'bridge',
  'files',
  'git-context',
  'identity',
  'policy',
  'postinstall',
])
  await copyFile(
    join(source, `${file}.cjs`),
    join(target, '.install-collector', `${file}.cjs`)
  );
console.log(`Assembled install collector for ${pkg.name}`);
