// SPDX-License-Identifier: MIT
// Generated by scripts/stripe/sync-products.ts. Do not edit by hand.
import type { TierSlug } from './tiers.config';

export const STRIPE_PRICE_IDS: Partial<Record<Exclude<TierSlug, 'community' | 'enterprise'>, string>> = {
  app_deployment: "price_1TZbHyGYRsLErhxb57O1CSEG",
  developer_seat: "price_1TZbHxGYRsLErhxb2u82hupX",
  indie: "price_1TZbHxGYRsLErhxbQfo00q9Q",
};
