// SPDX-License-Identifier: MIT
// Generated by scripts/stripe/sync-products.ts. Do not edit by hand.
import type { TierSlug, BillingCycle } from './tiers.config';

type BuyableSlug = Exclude<TierSlug, 'community' | 'enterprise'>;

export const STRIPE_PRICE_IDS: Partial<Record<BuyableSlug, Record<BillingCycle, string>>> = {
  developer_seat: { monthly: "price_1TapR1GYRsLErhxb83221xMU", annual: "price_1TapR1GYRsLErhxb67dc67h1" },
  team: { monthly: "price_1TapR2GYRsLErhxbBbrJMLpk", annual: "price_1TapR2GYRsLErhxbYsWAkYuE" },
};
