// SPDX-License-Identifier: MIT
// Generated by scripts/stripe/sync-products.ts. Do not edit by hand.
import type { TierSlug, BillingCycle } from './tiers.config';

type BuyableSlug = Exclude<TierSlug, 'community' | 'enterprise'>;

// Empty stub — run `STRIPE_SECRET_KEY=sk_... pnpm tsx scripts/stripe/sync-products.ts`
// to populate. Until that runs, the checkout API returns a 503 with a helpful
// message.
export const STRIPE_PRICE_IDS: Partial<Record<BuyableSlug, Record<BillingCycle, string>>> = {};
