import { validateRuntimeParentOrigins } from '@threadplane/cockpit-runtime-bridge';

export const GENERATED_RUNTIME_PARENT_ORIGINS_MODULE =
  'libs/cockpit-runtime-bridge/src/lib/generated-runtime-parent-origins.ts';

const RUNTIME_CONNECT_SOURCES = [
  "'self'",
  'https:',
  'http://localhost:*',
  'http://127.0.0.1:*',
  'http://[::1]:*',
] as const;

export interface RuntimeParentOriginPolicy {
  readonly childAllowedParentOrigins: readonly string[];
  readonly cspFrameAncestors: readonly string[];
  readonly compiledChildModule: string;
  readonly deploymentHeaders: Readonly<{
    'Content-Security-Policy': string;
    'Referrer-Policy': 'origin';
  }>;
}

function isSourceRecord(
  value: unknown
): value is { readonly baseOrigins: unknown } {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) {
    return false;
  }
  const prototype = Object.getPrototypeOf(value);
  if (prototype !== Object.prototype && prototype !== null) return false;
  const keys = Reflect.ownKeys(value);
  return keys.length === 1 && keys[0] === 'baseOrigins';
}

function invalidPolicy(): never {
  throw new Error('Invalid runtime parent origin policy');
}

function renderCompiledChildModule(origins: readonly string[]): string {
  return `// This file is generated by scripts/generate-runtime-parent-origins.ts.\n// Do not edit it independently of runtime-parent-origins.json.\nexport const GENERATED_RUNTIME_PARENT_ORIGINS = Object.freeze(${JSON.stringify(
    origins,
    null,
    2
  )} as const);\n`;
}

export function parseRuntimeParentPreviewOrigins(
  input: string | undefined
): readonly string[] {
  if (input === undefined || input === '') return Object.freeze([]);
  const previews = input.split(/\r?\n/).filter((origin) => origin !== '');
  for (const preview of previews) {
    if (validateRuntimeParentOrigins([preview]) === null)
      return invalidPolicy();
  }
  return Object.freeze(previews);
}

export function generateRuntimeParentOriginPolicy(
  source: unknown,
  ciPreviewOrigins: unknown
): RuntimeParentOriginPolicy {
  try {
    if (!isSourceRecord(source) || !Array.isArray(ciPreviewOrigins)) {
      return invalidPolicy();
    }

    const baseOrigins = validateRuntimeParentOrigins(source.baseOrigins);
    if (
      baseOrigins === null ||
      !baseOrigins.includes('https://threadplane.ai') ||
      baseOrigins.includes('https://cockpit.threadplane.ai')
    ) {
      return invalidPolicy();
    }

    const previews: string[] = [];
    for (const preview of ciPreviewOrigins) {
      const validated = validateRuntimeParentOrigins([preview]);
      if (validated === null) return invalidPolicy();
      previews.push(validated[0]);
    }

    const merged = [...new Set([...baseOrigins, ...previews])];
    const complete = validateRuntimeParentOrigins(merged);
    if (
      complete === null ||
      complete.includes('https://cockpit.threadplane.ai')
    ) {
      return invalidPolicy();
    }

    const childAllowedParentOrigins = Object.freeze([...complete]);
    const cspFrameAncestors = Object.freeze([...complete]);
    const deploymentHeaders = Object.freeze({
      'Content-Security-Policy': [
        "default-src 'self'",
        "script-src 'self'",
        "style-src 'self' 'unsafe-inline'",
        "img-src 'self' data: https:",
        `connect-src ${RUNTIME_CONNECT_SOURCES.join(' ')}`,
        `frame-ancestors ${cspFrameAncestors.join(' ')}`,
      ].join('; '),
      'Referrer-Policy': 'origin' as const,
    });

    return Object.freeze({
      childAllowedParentOrigins,
      cspFrameAncestors,
      compiledChildModule: renderCompiledChildModule(childAllowedParentOrigins),
      deploymentHeaders,
    });
  } catch {
    return invalidPolicy();
  }
}
