// SPDX-License-Identifier: MIT
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '../../../..');

function readDotEnv() {
  const envPath = resolve(repoRoot, '.env');
  if (!existsSync(envPath)) return {};
  const raw = readFileSync(envPath, 'utf8');
  const out = {};
  for (const line of raw.split('\n')) {
    const m = line.match(/^([A-Z_][A-Z0-9_]*)=(.*)$/);
    if (m) out[m[1]] = m[2].replace(/^"|"$/g, '');
  }
  return out;
}

const env = { ...readDotEnv(), ...process.env };
const key = env.GOOGLE_MAPS_API_KEY ?? '';

const targetPath = resolve(__dirname, '../src/environments/generated-keys.local.ts');
const contents = `// SPDX-License-Identifier: MIT
// AUTO-GENERATED by scripts/inject-env.mjs. Do not edit by hand.
export const GENERATED_KEYS = {
  googleMaps: ${JSON.stringify(key)},
} as const;
`;
writeFileSync(targetPath, contents);
console.log(`[inject-env] wrote generated-keys.local.ts (key length: ${key.length})`);
