// SPDX-License-Identifier: MIT
// AUTOGENERATED by libs/licensing/scripts/generate-public-key.mjs — do not edit.
// Source: dev-fixture
export const LICENSE_PUBLIC_KEY_HEX = '793132582f3d39dcd46cc6fd010c6c4b10f1225132e7de71fbcb45788ea5afde' as const;
