// This file is generated by scripts/generate-runtime-parent-origins.ts.
// Do not edit it independently of runtime-parent-origins.json.
export const GENERATED_RUNTIME_PARENT_ORIGINS = Object.freeze([
  "https://threadplane.ai",
  "http://localhost:3000",
  "http://127.0.0.1:3000",
  "http://localhost:4308",
  "http://127.0.0.1:4308"
] as const);
